### ISSUE TITLE
Make hardcoded deps to cleanup and tag-script optional?

### ISSUE THREAD

**Issue by tmerse** [mturquette/ghar-email#1]
Tank for the useful notmuch tag sync utility

Unfortunately the script won't run, if either one of those files doesn't exist:

```
TAG_SCRIPT=$HOME/.local/bin/tag_mailing_lists
CLEANUP_SCRIPT=$HOME/.local/bin/tag_clean_up
```

[source](https://github.com/mturquette/ghar-email/blob/master/.local/bin/maildir-notmuch-sync#L189-L190)

Maybe it would be more convenient, if those are only executed if they exist.

**Comment by mturquette** [comment]
Thanks for the bug report. I plan to pass those scripts in as args some day but in the mean time I've simply checked for their existence before trying to execute them, per your suggestion. Let me know if this solves the problem for you!

**Comment by tmerse** [comment]
I hardcoded different files. But at a first glance this looks like I imagined.
